version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
       - postgre_volume:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    postgre_volume:
